# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksmodel', '0002_auto_20170622_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='tile',
            new_name='title',
        ),
    ]
